import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { createClerkSupabaseClient } from "@/lib/supabase/clerk-client";
import { handleApiError, ApiError, ErrorCodes } from "@/lib/errors";

export const dynamic = "force-dynamic";

/**
 * GET /api/briefs/count
 * Returns the number of briefs generated by the authenticated user
 */
export async function GET(request: NextRequest) {
  const requestId = crypto.randomUUID();

  try {
    // Verify authentication
    const { userId } = await auth();

    if (!userId) {
      throw new ApiError(401, "Please log in to view brief count", ErrorCodes.UNAUTHORIZED);
    }

    const supabase = await createClerkSupabaseClient();

    // Query user_briefs table using the get_brief_count function
    const { data, error } = await supabase
      .rpc('get_brief_count', { p_user_id: userId });

    if (error) {
      throw new ApiError(
        500,
        "Failed to fetch brief count",
        ErrorCodes.DATABASE_ERROR,
        error
      );
    }

    const briefCount = data || 0;

    return NextResponse.json({
      count: briefCount,
    });
  } catch (error) {
    return handleApiError(error, requestId);
  }
}
